In [1]:
import pandas 

In [2]:
dataset = pandas.read_csv("SalaryData.csv")

In [3]:
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
x = dataset['YearsExperience'].values.reshape(-1, 1)

In [5]:
y = dataset['Salary'].values.reshape(-1, 1)

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [7]:
x_test

array([[9.6],
       [1.3],
       [6.8],
       [4.1],
       [5.3],
       [3.2]])

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model = LinearRegression()

In [10]:
model.fit(x_train, y_train)

LinearRegression()

In [11]:
# predict the value that tends to y_test
model.predict(x_test)

array([[117108.29209528],
       [ 37164.37911029],
       [ 90139.26120878],
       [ 64133.40999679],
       [ 75691.56609101],
       [ 55464.79292613]])

In [12]:
model.predict([[1.5]])

array([[39090.73845932]])

In [13]:
model.coef_

array([[9631.79674518]])

In [14]:
model.intercept_

array([24643.04334155])

In [15]:
# store the trained model into hard disk so that we don't have to train the model again and again
import joblib

In [17]:
joblib.dump(model, "salary_predictor.trained")

['salary_predictor.trained']

In [18]:
import joblib

In [19]:
model = joblib.load('salary_predictor.trained')

In [21]:
model.predict([[2]])

array([[43906.63683191]])